### ISSUE TITLE
Backend tasks to resolve prior to launch

### ISSUE THREAD

**Issue by canonsawrey** [canonsawrey/DeltNU-iOS#43]
Following tasks will unblock me from publishing:
- [x] Community service hours GET endpoint
- [x] Minutes PDFs endpoint within app (without CSRF token)
- [x] Return 403/302/whatever @Er1cG1ft wants for making a request with an expired token (currently gives back 200)
- [ ] (Optional) DeltNU google calendar events endpoint
- [x] (Optional) Community service hours POST endpoint

**Comment by Er1cG1ft** [comment]
Service hours endpoints:
`/servicehours/app_index` will return a JSON object with the following fields.  Should be everything needed to display stats if you want to.  Let me know if there's a better way to return this data.
- `hours`: individual hours for the current semester
- `total_hours`: total number of hours for current semester
- `hours_goal`: goal for the current semester from admin settings
- `progress`: total_hours / hours_goal as an integer (for percentage)
- `top_users`: top 5 users with their aggregate hours
- `toporgs`: top 5 organizations with their aggregate hours (yeah sorry, missed the underscore)
- `hours_per_user`: each user with their total aggregate hours for the semester

`/servicehours/app_archive` will return all hours for semesters occurring before the current one

Bad cookie request will return a 403 with `{"response":"Invalid cookie"}` as the payload

For the minutes PDF, I didn't stop to think about opening up the PDFs to not require a token.  Not sure I want to do this for security.  Is there another way we can do this?  Can I send the contents of the PDF as binary to display? Open to whatever as long as we can protect the endpoint.

**Comment by canonsawrey** [comment]
Yeah that'll for sure work. If anything its overkill, but that just means its extensible lol.
As for the minutes - is there any reason this is different from the others? Like why can vote not need CSRF but minutes does? Is there any reason the session cookie is not enough protection?

**Comment by canonsawrey** [comment]
403 seems to be working btw

**Comment by Er1cG1ft** [comment]
Lol, I confused CSRF token with Auth Cookie. Guess that's what happens when you take a 2 week break from dev.  I'll fix that and a service hours POST endpoint today.

For the calendar stuff, I actually forgot I finished a google calendar event import functionality.  The problem is it requires manual import of all the events and some data tweaking (required event, sobers needed, etc).  Would be interested to hear your thoughts on how this would work, do we periodically sync with the google calendar and just display these events as-is?  Do we have the secretary add custom fields to google events (idk if this is possible) so there's 1 point of truth?

**Comment by canonsawrey** [comment]
I have EBoard tonight, I will ask for thoughts about this. My opinion is just import as is, maybe sync each night at midnight?

**Comment by canonsawrey** [comment]
If we do want to support "tagging" events, we could tell the secretary to add tags like:
[REQUIRED], [SOBERS:2] or whatever to the details section of the event

**Comment by canonsawrey** [comment]
And then just parse it

**Comment by Er1cG1ft** [comment]
Oooh I like that formatting idea.  Sounds good though.

**Comment by Er1cG1ft** [comment]
Added service hours POST endpoint and turned off CSRF for `minutes/:id`.  You should be able send a service hour payload that's the same format as what you get from the index endpoint, but let me know if you can't get it to work easily.

**Comment by canonsawrey** [comment]
Webview for minutes working

**Comment by Er1cG1ft** [comment]
lets GO
